/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "surface-container-high": "#e8e8e8",
        "surface-tint": "#00C4B5",
        "secondary-fixed-dim": "#FFB8D2",
        "surface": "#f9f9f9",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#474747",
        "on-secondary-container": "#4A0021",
        "inverse-surface": "#2f3131",
        "on-tertiary-container": "#646363",
        "surface-container-highest": "#e2e2e2",
        "on-primary-fixed": "#00201D",
        "surface-container": "#eeeeee",
        "surface-container-low": "#f3f3f4",
        "inverse-primary": "#5EE8DC",
        "tertiary-fixed": "#e4e2e1",
        "surface-bright": "#f9f9f9",
        "on-tertiary-fixed": "#1b1c1c",
        "primary-container": "#B2F5EA",
        "on-primary-container": "#003B36",
        "outline": "#6f7973",
        "secondary": "#FF6B9E",
        "on-surface": "#1a1c1c",
        "tertiary": "#5f5e5e",
        "on-secondary-fixed": "#310014",
        "surface-variant": "#e2e2e2",
        "secondary-container": "#FFD9E6",
        "background": "#f9f9f9",
        "surface-dim": "#dadada",
        "on-surface-variant": "#3f4944",
        "on-primary-fixed-variant": "#00514A",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#e3e1e0",
        "primary-fixed": "#7DF5EA",
        "on-background": "#1a1c1c",
        "on-secondary-fixed-variant": "#7A0035",
        "secondary-fixed": "#FFD9E6",
        "primary-fixed-dim": "#5EE8DC",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#c8c6c6",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f0f1f1",
        "primary": "#00C4B5",
        "outline-variant": "#bfc9c2"
      },
      "borderRadius": {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      "spacing": {
        "gutter": "20px",
        "lg": "40px",
        "md": "24px",
        "base": "4px",
        "margin-desktop": "40px",
        "sm": "16px",
        "xs": "8px",
        "container-max": "1280px",
        "xl": "64px",
        "margin-mobile": "20px"
      },
      "fontFamily": {
        "body-md": ["Hanken Grotesk"],
        "label-md": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "label-sm": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "title-md": ["Hanken Grotesk"]
      },
      "fontSize": {
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "title-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
